/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tree2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.003']} position={[1.09, 3.72, -2.12]} scale={0.68} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.003']} position={[0.14, 4.28, -1.75]} rotation={[0.36, 0.52, 0.74]} scale={0.76} />
      <mesh geometry={nodes.Icosphere002.geometry} material={materials['Material.003']} position={[-1.49, 4.47, -0.97]} rotation={[0.36, 0.52, 0.74]} scale={1.08} />
      <mesh geometry={nodes.Icosphere003.geometry} material={materials['Material.003']} position={[-2.22, 3.68, 0.43]} rotation={[0.54, 0.83, 0.95]} scale={0.89} />
      <mesh geometry={nodes.Icosphere004.geometry} material={materials['Material.003']} position={[-0.09, 4.3, -0.57]} rotation={[0.18, 0.42, 0.37]} scale={0.76} />
      <mesh geometry={nodes.Icosphere005.geometry} material={materials['Material.003']} position={[-1.41, 2.78, 1.49]} rotation={[0.27, 0.84, 0.12]} scale={0.76} />
      <mesh geometry={nodes.Icosphere006.geometry} material={materials['Material.003']} position={[-1.47, 3.83, 1.29]} rotation={[0.33, 0.88, 0.33]} scale={0.76} />
      <mesh geometry={nodes.Icosphere007.geometry} material={materials['Material.003']} position={[-0.66, 4.23, 0.34]} rotation={[0.36, 0.52, 0.74]} scale={0.85} />
      <mesh geometry={nodes.Icosphere008.geometry} material={materials['Material.003']} position={[0.32, 3.85, 0.8]} rotation={[-0.24, -0.16, 0.09]} scale={0.84} />
      <mesh geometry={nodes.Icosphere009.geometry} material={materials['Material.002']} position={[0.87, 4.02, -0.16]} rotation={[0.56, 0.69, -0.05]} scale={0.64} />
      <mesh geometry={nodes.Icosphere010.geometry} material={materials['Material.002']} position={[0.84, 3.84, -0.99]} rotation={[0.54, 0.68, -0.05]} scale={0.64} />
    </group>
  )
}

useGLTF.preload('/tree2.glb')
